# Generated by Django 5.2.16 on 2026-07-17 22:04

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('genotype', models.CharField(blank=True, max_length=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('chronic_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_key_salt', models.BinaryField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('read_timeline', 'Read timeline'), ('read_prescriptions', 'Read prescriptions'), ('read_lab_results', 'Read lab results'), ('read_all', 'Read all')], default='read_timeline', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, null=True)),
                ('granted_to_doctor', models.ForeignKey(db_column='granted_to_doctor', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_grants',
                'constraints': [models.UniqueConstraint(fields=('patient', 'granted_to_doctor', 'scope'), name='uq_consent_grant')],
            },
        ),
        migrations.CreateModel(
            name='ConsentTermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_type', models.CharField(choices=[('terms_of_service', 'Terms of service'), ('privacy_notice', 'Privacy notice'), ('health_profile', 'Health profile'), ('health_timeline', 'Health timeline'), ('marketing', 'Marketing'), ('analytics', 'Analytics')], max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('granted', models.BooleanField()),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_terms_acceptances',
                'constraints': [models.UniqueConstraint(fields=('user', 'consent_type', 'version'), name='uq_consent_terms')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('document_type', models.CharField(choices=[('medical_license', 'Medical license'), ('national_id', 'National ID'), ('proof_of_address', 'Proof of address'), ('qualification_certificate', 'Qualification certificate'), ('lab_result', 'Lab result'), ('prescription', 'Prescription'), ('insurance_card', 'Insurance card'), ('other', 'Other')], max_length=30)),
                ('storage_key', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='pending', max_length=20)),
                ('scan_result', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['owner', 'document_type'], name='idx_doc_owner_type')],
            },
        ),
        migrations.CreateModel(
            name='HealthTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('entry_type', models.CharField(choices=[('symptom_log', 'Symptom log'), ('diagnosis_note', 'Diagnosis note'), ('prescription', 'Prescription'), ('lab_result', 'Lab result'), ('patient_note', 'Patient note'), ('vaccination', 'Vaccination'), ('allergy_record', 'Allergy record')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content_encrypted', models.BinaryField()),
                ('content_iv', models.BinaryField()),
                ('key_version', models.SmallIntegerField(default=1)),
                ('visibility', models.CharField(choices=[('patient_only', 'Patient only'), ('shared_with_current_doctor', 'Shared with current doctor'), ('shared_with_all_future_doctors', 'Shared with all future doctors')], default='patient_only', max_length=40)),
                ('attachment_keys', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('icd10_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('is_pinned', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('authored_by', models.ForeignKey(db_column='authored_by', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_timeline_entries',
                'indexes': [models.Index(fields=['patient', '-created_at'], name='idx_timeline_patient')],
            },
        ),
    ]
