-- Reverse of 0003: drop triggers, then functions, then revert the reconciliation ALTERs.
DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
DROP TRIGGER IF EXISTS trg_user_auth_providers_updated_at ON user_auth_providers;
DROP TRIGGER IF EXISTS trg_device_tokens_updated_at ON device_tokens;
DROP TRIGGER IF EXISTS trg_service_categories_updated_at ON service_categories;
DROP TRIGGER IF EXISTS trg_feature_flags_updated_at ON feature_flags;
DROP TRIGGER IF EXISTS trg_notification_templates_updated_at ON notification_templates;
DROP TRIGGER IF EXISTS trg_notification_log_updated_at ON notification_log;
DROP TRIGGER IF EXISTS trg_notification_preferences_updated_at ON notification_preferences;
DROP TRIGGER IF EXISTS trg_payment_transactions_updated_at ON payment_transactions;
DROP TRIGGER IF EXISTS trg_payouts_updated_at ON payouts;
DROP TRIGGER IF EXISTS trg_bank_accounts_updated_at ON bank_accounts;
DROP TRIGGER IF EXISTS trg_patient_profiles_updated_at ON patient_profiles;
DROP TRIGGER IF EXISTS trg_specializations_updated_at ON specializations;
DROP TRIGGER IF EXISTS trg_clinics_updated_at ON clinics;
DROP TRIGGER IF EXISTS trg_doctor_profiles_updated_at ON doctor_profiles;
DROP TRIGGER IF EXISTS trg_doctor_qualifications_updated_at ON doctor_qualifications;
DROP TRIGGER IF EXISTS trg_clinic_affiliations_updated_at ON clinic_affiliations;
DROP TRIGGER IF EXISTS trg_availability_templates_updated_at ON availability_templates;
DROP TRIGGER IF EXISTS trg_slots_updated_at ON slots;
DROP TRIGGER IF EXISTS trg_pre_consultation_form_templates_updated_at ON pre_consultation_form_templates;
DROP TRIGGER IF EXISTS trg_appointments_updated_at ON appointments;
DROP TRIGGER IF EXISTS trg_health_timeline_entries_updated_at ON health_timeline_entries;
DROP TRIGGER IF EXISTS trg_consent_grants_updated_at ON consent_grants;
DROP TRIGGER IF EXISTS trg_reviews_updated_at ON reviews;
DROP TRIGGER IF EXISTS trg_documents_updated_at ON documents;
DROP TRIGGER IF EXISTS trg_telehealth_sessions_updated_at ON telehealth_sessions;
DROP TRIGGER IF EXISTS trg_audit_log_no_update ON audit_log;
DROP TRIGGER IF EXISTS trg_audit_log_no_delete ON audit_log;
DROP TRIGGER IF EXISTS trg_audit_log_no_truncate ON audit_log;
DROP TRIGGER IF EXISTS trg_audit_log_chain ON audit_log;
DROP FUNCTION IF EXISTS audit_log_chain();
DROP FUNCTION IF EXISTS audit_log_reject_mutation();
DROP FUNCTION IF EXISTS set_updated_at();
ALTER TABLE audit_log ALTER COLUMN row_hash DROP NOT NULL;
ALTER TABLE patient_profiles ALTER COLUMN patient_key_salt DROP NOT NULL;
ALTER TABLE patient_profiles ALTER COLUMN patient_key_salt DROP DEFAULT;
