# Generated by Django 5.2.16 on 2026-07-17 22:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('cash', 'Cash')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.IntegerField()),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('provider_response', models.JSONField(default=dict)),
                ('refunded_amount', models.IntegerField(default=0)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('payer', models.ForeignKey(db_column='payer_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'indexes': [models.Index(fields=['payer', '-created_at'], name='payment_tra_payer_i_855b08_idx'), models.Index(fields=['appointment'], name='payment_tra_appoint_c257eb_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx'), models.Index(fields=['provider_reference'], name='payment_tra_provide_73d4ff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonneg'), models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='payment_refund_nonneg'), models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('amount'))), name='refund_lte_amount')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('cash', 'Cash')], default='paystack', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gross_amount', models.IntegerField()),
                ('platform_fee', models.IntegerField(default=0)),
                ('tax_withheld_minor', models.IntegerField(default=0)),
                ('tax_rate_bps', models.SmallIntegerField(default=0)),
                ('net_amount', models.IntegerField()),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('appointment_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('provider_response', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts',
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='payouts_recipie_1166a3_idx'), models.Index(fields=['status'], name='payouts_status_20cd29_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('net_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_amount'), '-', models.F('platform_fee')), '-', models.F('tax_withheld_minor')))), name='payout_net_check'), models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='payout_period_check'), models.CheckConstraint(condition=models.Q(('tax_rate_bps__gte', 0), ('tax_rate_bps__lte', 2500)), name='payout_tax_rate_range')],
            },
        ),
    ]
