# Generated by Django 5.2.16 on 2026-07-17 22:04

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=300, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(default='GH', max_length=2)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=320, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_storage_key', models.TextField(blank=True, null=True)),
                ('photos_storage_keys', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending_review', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='unverified', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.SmallIntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_issuing_council', models.CharField(blank=True, max_length=200, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_storage_key', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending_review', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_punctuality_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_communication_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_medical_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('profile_completeness_pct', models.SmallIntegerField(default=0)),
                ('response_rate_pct', models.SmallIntegerField(default=100)),
                ('slot_confidence_score', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('profile_views', models.IntegerField(default=0)),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('is_profile_active', models.BooleanField(default=True)),
                ('profile_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('embedding_content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_code', models.CharField(max_length=10)),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native')], default='fluent', max_length=20)),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_languages',
            },
        ),
        migrations.CreateModel(
            name='ClinicAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulting_room', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary_clinic', models.BooleanField(default=False)),
                ('consultation_fee', models.IntegerField()),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('telehealth_fee', models.IntegerField(blank=True, null=True)),
                ('cancellation_free_window_hours', models.SmallIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.clinic')),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'clinic_affiliations',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.SmallIntegerField(default=30)),
                ('booking_mode', models.CharField(choices=[('in_person', 'In person'), ('telehealth', 'Telehealth'), ('either', 'Either')], default='either', max_length=20)),
                ('buffer_minutes', models.SmallIntegerField(default=0)),
                ('max_patients_per_slot', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('clinic_affiliation', models.ForeignKey(blank=True, db_column='clinic_affiliation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.clinicaffiliation')),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'availability_templates',
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('country_code', models.CharField(default='GH', max_length=2)),
                ('year_obtained', models.SmallIntegerField(blank=True, null=True)),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_qualifications',
            },
        ),
        migrations.CreateModel(
            name='SavedDoctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_doctors',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('booking_mode', models.CharField(choices=[('in_person', 'In person'), ('telehealth', 'Telehealth'), ('either', 'Either')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='available', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('block_reason', models.TextField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(blank=True, db_column='blocked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clinic_affiliation', models.ForeignKey(blank=True, db_column='clinic_affiliation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.clinicaffiliation')),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
                ('template', models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.availabilitytemplate')),
            ],
            options={
                'db_table': 'slots',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='doctors.specialization')),
            ],
            options={
                'db_table': 'specializations',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
                ('specialization', models.ForeignKey(db_column='specialization_id', on_delete=django.db.models.deletion.RESTRICT, to='doctors.specialization')),
            ],
            options={
                'db_table': 'doctor_specializations',
            },
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['location'], name='idx_clinics_location'),
        ),
        migrations.AddConstraint(
            model_name='doctorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('rating_avg__gte', 0), ('rating_avg__lte', 5)), name='doctor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='doctorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('slot_confidence_score__gte', 0), ('slot_confidence_score__lte', 1)), name='doctor_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='doctorlanguage',
            constraint=models.UniqueConstraint(fields=('doctor_profile', 'language_code'), name='uq_doctor_language'),
        ),
        migrations.AddConstraint(
            model_name='clinicaffiliation',
            constraint=models.UniqueConstraint(fields=('doctor_profile', 'clinic'), name='uq_clinic_affiliation'),
        ),
        migrations.AddConstraint(
            model_name='clinicaffiliation',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_free_window_hours__gte', 0), ('cancellation_free_window_hours__lte', 168)), name='affiliation_free_window_range'),
        ),
        migrations.AddConstraint(
            model_name='availabilitytemplate',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='template_time_check'),
        ),
        migrations.AddConstraint(
            model_name='availabilitytemplate',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__in', [15, 20, 30, 45, 60])), name='template_slot_duration'),
        ),
        migrations.AddConstraint(
            model_name='saveddoctor',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor_profile'), name='uq_saved_doctor'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['slot_date', 'status'], name='idx_slots_date_status'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['start_at'], name='idx_slots_start_at'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('doctor_profile', 'slot_date', 'start_time'), name='uq_slot'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_time_check'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='slot_instant_check'),
        ),
        migrations.AddConstraint(
            model_name='doctorspecialization',
            constraint=models.UniqueConstraint(fields=('doctor_profile', 'specialization'), name='uq_doctor_specialization'),
        ),
    ]
