# Generated by Django 5.2.16 on 2026-07-17 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(blank=True, choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled_by_patient', 'Cancelled by patient'), ('cancelled_by_doctor', 'Cancelled by doctor'), ('cancelled_by_platform', 'Cancelled by platform'), ('no_show_patient', 'No-show (patient)'), ('no_show_doctor', 'No-show (doctor)')], max_length=25, null=True)),
                ('to_status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled_by_patient', 'Cancelled by patient'), ('cancelled_by_doctor', 'Cancelled by doctor'), ('cancelled_by_platform', 'Cancelled by platform'), ('no_show_patient', 'No-show (patient)'), ('no_show_doctor', 'No-show (doctor)')], max_length=25)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'appointment_status_history',
            },
        ),
        migrations.CreateModel(
            name='PreConsultationFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fields', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'pre_consultation_form_templates',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('rating_overall', models.SmallIntegerField()),
                ('rating_punctuality', models.SmallIntegerField()),
                ('rating_communication', models.SmallIntegerField()),
                ('rating_medical', models.SmallIntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('doctor_reply', models.TextField(blank=True, null=True)),
                ('doctor_replied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='TelehealthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='daily.co', max_length=50)),
                ('room_name', models.CharField(max_length=255)),
                ('room_url', models.TextField()),
                ('doctor_joined_at', models.DateTimeField(blank=True, null=True)),
                ('patient_joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('provider_session_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'telehealth_sessions',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled_by_patient', 'Cancelled by patient'), ('cancelled_by_doctor', 'Cancelled by doctor'), ('cancelled_by_platform', 'Cancelled by platform'), ('no_show_patient', 'No-show (patient)'), ('no_show_doctor', 'No-show (doctor)')], default='requested', max_length=25)),
                ('booking_mode', models.CharField(choices=[('in_person', 'In person'), ('telehealth', 'Telehealth'), ('either', 'Either')], max_length=20)),
                ('consultation_fee', models.IntegerField()),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('pre_consultation_responses', models.JSONField(default=dict)),
                ('patient_notes', models.TextField(blank=True, null=True)),
                ('estimated_wait_minutes', models.SmallIntegerField(default=0)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('telehealth_room_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telehealth_room_url', models.TextField(blank=True, null=True)),
                ('telehealth_patient_url', models.TextField(blank=True, null=True)),
                ('telehealth_room_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('no_show_marked_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_recommended', models.BooleanField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, db_column='cancelled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinic_affiliation', models.ForeignKey(blank=True, db_column='clinic_affiliation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.clinicaffiliation')),
                ('doctor_profile', models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.RESTRICT, to='doctors.doctorprofile')),
                ('follow_up_appointment', models.ForeignKey(blank=True, db_column='follow_up_appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.appointment')),
                ('no_show_marked_by', models.ForeignKey(blank=True, db_column='no_show_marked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
