# Generated by Django 5.2.16 on 2026-07-17 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, db_column='payment_transaction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.RESTRICT, to='doctors.slot'),
        ),
        migrations.AddField(
            model_name='appointmentstatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentstatushistory',
            name='appointment',
            field=models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='preconsultationformtemplate',
            name='doctor_profile',
            field=models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='form_template',
            field=models.ForeignKey(blank=True, db_column='form_template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.preconsultationformtemplate'),
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.RESTRICT, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='review',
            name='doctor_profile',
            field=models.ForeignKey(db_column='doctor_profile_id', on_delete=django.db.models.deletion.RESTRICT, to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telehealthsession',
            name='appointment',
            field=models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatushistory',
            index=models.Index(fields=['appointment', '-created_at'], name='idx_appt_hist'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-created_at'], name='idx_appt_patient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor_profile', '-created_at'], name='idx_appt_doctor'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['slot'], name='idx_appt_slot'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='idx_appt_status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('consultation_fee__gte', 0)), name='appt_fee_nonneg'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['doctor_profile', '-created_at'], name='idx_review_doctor'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating_overall__gte', 1), ('rating_overall__lte', 5)), name='review_overall_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating_punctuality__gte', 1), ('rating_punctuality__lte', 5)), name='review_punctuality_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating_communication__gte', 1), ('rating_communication__lte', 5)), name='review_communication_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating_medical__gte', 1), ('rating_medical__lte', 5)), name='review_medical_range'),
        ),
    ]
